framework:
    mailer:
        dsn: '%env(MAILER_DSN)%' # 'null://null' : désactive l'envoie de mail
        envelope:
            recipients: ['dacostasteven91@gmail.com'] # envoie tous les mails à cette adresse
